// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// SchemaMigration is the predicate function for schemamigration builders.
type SchemaMigration func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
